### ISSUE TITLE
为什么引入了那么多lib下的文件，不能支持引用dist后的文件吗

### ISSUE THREAD

**Issue by trainGitHub** [fex-team/fis3-hook-node_modules#11]
页面上部分代码 

<script type="text/javascript" src="/client/static/mod.js"></script>

<script type="text/javascript" src="/node_modules/process/browser.js"></script>

<script type="text/javascript" src="/node_modules/react/lib/ReactCurrentOwner.js"></script>

<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/ExecutionEnvironment.js"></script>

<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/invariant.js"></script>

<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/toArray.js"></script>

<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/createArrayFromMixed.js"></script>

<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/getMarkupWrap.js"></script>

<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/createNodesFromMarkup.js"></script>

<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/emptyFunction.js"></script>

<script type="text/javascript" src="/node_modules/react/lib/Danger.js"></script>

<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/keyMirror.js"></script>

<script type="text/javascript" src="/node_modules/react/lib/ReactMultiChildUpdateTypes.js"></script>

**Comment by ascoders** [comment]
哪儿有lib

**Comment by trainGitHub** [comment]
编译后的文件类似这样的链接很多，不能直接引用单个的react吗

``` html
<script type="text/javascript" src="/node_modules/react/lib/Danger.js"></script>
<script type="text/javascript" src="/node_modules/react/node_modules/fbjs/lib/keyMirror.js"></script>
<script type="text/javascript" src="/node_modules/react/lib/ReactMultiChildUpdateTypes.js"></script>
<script type="text/javascript" src="/node_modules/react/lib/ReactPerf.js"></script>
<script type="text/javascript" src="/node_modules/react/lib/setInnerHTML.js"></script>
```

**Comment by andycall** [comment]
react 项目本来文件就是散的。。这个得看它的package.json的main是怎么写的。。
这个我们做工具的没办法， 只能看发布包的人来判断了。。

不过你可以使用pack插件来吧所有打散的文件压缩在一起。
[fis3-packager-deps-pack](https://github.com/fex-team/fis3-packager-deps-pack)

**Comment by trainGitHub** [comment]
知道了，多谢
