### ISSUE TITLE
fis3-hook-node_modules + antd 遇到诡异的问题了！

### ISSUE THREAD

**Issue by codering** [fex-team/fis3-hook-node_modules#13]
**用antd做了一个表单验证， fis3编译的代码验证有问题（会同时提示2个错误信息），antd自身做的是没这个问题的。**

fis3 编译生成的demo : http://sandbox.runjs.cn/show/aa58mp8v.  
直接用已合并的antd做的的demo:  http://codepen.io/coderingz/pen/EKXjZa?editors=1010

fis3版本是  3.3.21
antd版本是 0.12.12
react版本 0.14.7

以下是demo源码

``` js

const {Form, Input} = antd
const FormItem = Form.Item

const Reports = (props) => {

  const { getFieldProps } = props.form;

   const emailProps = getFieldProps('email',{
     //validateFirst: true,
     validate: [{
         rules: [
           { required: true, message: '必须填写邮箱地址' },
         ],
         trigger: 'onBlur',
       }, {
         rules: [
           { type: 'email', message: '请输入正确的邮箱地址' },
         ],
         trigger: ['onBlur','onChange'],
       }]
   });

  return (
      <Form horizontal form={props.form}>
        <FormItem label="邮箱："   >
          <Input {...emailProps} placeholder="请输入邮箱" />
        </FormItem>
      </Form>
  )
}

const Demo = Form.create()(Reports)

ReactDOM.render(<Demo />,
  document.getElementById('container')
);

```

**Comment by andycall** [comment]
有么。。。

![image](https://cloud.githubusercontent.com/assets/4409743/14048666/b3e5fa4c-f2ea-11e5-9c56-67722ee9c3a1.png)
![image](https://cloud.githubusercontent.com/assets/4409743/14048669/b77bc984-f2ea-11e5-9a5f-db32e6c19d7d.png)

**Comment by codering** [comment]
@andycall  第一个demo不输入失去焦点的时候不是2个提示信息？

**Comment by andycall** [comment]
![demo](https://cloud.githubusercontent.com/assets/4409743/14059068/54ae8522-f370-11e5-9ee6-596667ad52d7.gif)

还是没发现。。

**Comment by codering** [comment]
额，我说的就是 “必须填写邮箱地址，请输入正确的邮箱地址” 。 按正常来说，只会出现“必须填写邮箱地址” 或者 “请输入正确的邮箱地址” ，这2个提示语句不应该同时出现。你看下第二个demo就知道了.

**Comment by andycall** [comment]
能别把代码压缩么。。- -。 都看不懂了

**Comment by codering** [comment]
我把完整的demo源码放到这里了 https://github.com/codering/form-demo

**Comment by andycall** [comment]
v1.1.5

**Comment by codering** [comment]
恩, ok了。 非常感谢！ 能问下是什么原因吗？

**Comment by andycall** [comment]
rc-form和rc-form-validation同时依赖一个async-validator. 不过版本不同。

主要还是最初构建依赖分析树有点问题。。有个地方把之前找到的版本对象给覆盖了.  后面即使对比版本发现是2个版本也只能找到一个async-validation的版本。

最后就造成了rc-form和rc-form-validation依赖同一个版本的包了。
