### ISSUE TITLE
TODO: ignore devDependencies for performance enhance.

### ISSUE THREAD

**Issue by 2betop** [fex-team/fis3-hook-node_modules#14]

**Comment by andycall** [comment]
我发现2.0性能没有1.0好诶. 慢了有1s

**Comment by 2betop** [comment]
没从 dependencies 里面读，而是所有 node_modules 目录都 load 一遍，应该就是这的问题。

**Comment by 2betop** [comment]
更新了一个版本，再对比看看？

**Comment by andycall** [comment]
[WARNI] Can't resolve `lodash` in file [/node_modules/fit-table/node_modules/fit-radio/lib/radio/index.js], did you miss `npm install lodash`?

爆出一堆warning。。。 demo也跑跪了。。

**Comment by 2betop** [comment]
lodash在 devDependencies 里面？

**Comment by andycall** [comment]
没有呀。。是在fit-radio的dependencies里面，没有在项目里。是一个模块的依赖。

**Comment by 2betop** [comment]
不科学啊，我尝试了下 fit-radio 没复现你说的这个问题，有可能跟后面的更新有关，你更新下试试，看是否解决？

**Comment by andycall** [comment]
你可以试试我在1.0里面的demo

**Comment by 2betop** [comment]
lodash 不是在 devDependencies 里面吗？https://github.com/fex-team/fis3-hook-node_modules/blob/1.0/demo/package.json#L49

**Comment by 2betop** [comment]
看来这个地方比较隐蔽，默认还是不要开启忽略 devDependencies
