### ISSUE TITLE
为什么 fis 不把这个设为默认

### ISSUE THREAD

**Issue by dd1994** [fex-team/fis3-hook-node_modules#15]
我看 readme 里提到的设置后可以用 require语法加载node_modules, css, js, image等资源文件，这不是比用 fis 默认的 `?__inline` 用法好的多么？

**Comment by dd1994** [comment]
另外那个 https://github.com/fis-components/components ，直接用这个 fis3-hook-node_modules 加上  `npm install` 不是很好吗，为什么要自己再造一个，大大增加维护成本，npm 上几十万个包不可能全部加进去吧?

**Comment by 2betop** [comment]
嗯， 后续会取代 components ，目前 node_modules 还在试水，所以还在继续使用。

**Comment by dd1994** [comment]
以后也会抛弃加 `?__inline` 这种写法，直接用 `require` 吗？

**Comment by 2betop** [comment]
require 只是 js 里面的能力，html 和 css 也需要内嵌其他资源的这个能力。so.. 不会抛弃。

**Comment by dd1994** [comment]
懂了，感谢🙏
