### ISSUE TITLE
与原定的目录结构不兼容

### ISSUE THREAD

**Issue by chenwery** [fex-team/fis3-hook-node_modules#19]
我的目录结构一部分内容如下：

![image](https://cloud.githubusercontent.com/assets/2362621/14454939/7aa355fc-00cf-11e6-81c5-29033b4b2d5a.png)

通过一下配置，实现一些require简写，

``` javascript

// modules/m/m.js => require('m')
fis.match(/^\/modules\/([^\/]+)\/\1\.jsx?$/, {
    id: '$1'
});

// pages/m/m.js => require('pages/m')
fis.match(/^\/pages\/([^\/]+)\/\1\.jsx?$/, {
    id: 'pages/$1'
});

```

使用了这个插件之后这些配置就没用了，会报这样的错：

```
[ERROR] Cannot find module...
```

必须使用下面的方式引用

``` javascript
require('/modules/m')
require('/pages/m')
```

比较不合理，有办法解决吗？

**Comment by chenwery** [comment]
还有，在项目本身自定义了一些hook来自定义require方式之后，会遇到同样的问题。例如https://github.com/imweb/fis3-hook-lego 会失效

**Comment by 2betop** [comment]
require 的简写，请试试 https://github.com/fex-team/fis3-hook-commonjs 这里面的 paths 和 packages 的配置，这个应该能用。

**Comment by chenwery** [comment]
@2betop 
和这个是同一个问题https://github.com/fex-team/fis3-hook-node_modules/issues/6  ，把resolve里的error捕获并避免fis编译终止可以解决问题
