### ISSUE TITLE
我安装了一个antd, 页面加载的时候出现错误，麻烦看下

### ISSUE THREAD

**Issue by codering** [fex-team/fis3-hook-node_modules#2]
我发现依赖 object-assign 的都被编译成 {} 
编译前

``` js
var _objectAssign = require('object-assign');

```

![image](https://cloud.githubusercontent.com/assets/2271825/13281647/07d4d9b2-db20-11e5-9bd2-2a38573b8dae.png)

编译后

``` js
var _objectAssign = {};
```

![image](https://cloud.githubusercontent.com/assets/2271825/13280766/d582adae-db1a-11e5-8da9-351dbc4f1f25.png)

**Comment by andycall** [comment]
发一下antd的版本号，我看下是不是package.json的browser属性的object-assign加了false

**Comment by andycall** [comment]
fixed 1.0.11, antd运行没问题了
