### ISSUE TITLE
报了一个错：Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by trainGitHub** [fex-team/fis3-hook-node_modules#22]
fis3 release -d ../
 [INFO] Currently running fis3 (/usr/local/Cellar/nvm/0.29.0/versions/node/v4.2.3/lib/node_modules/fis3/)
 δ 6ms
 Ω
 [WARNI] Did you mean process:start event?
 [ERROR] Cannot convert undefined or null to object

配置文加上下面的配置，就会出错，不知道是什么原因？
fis.hook('node_modules', {
    useDev: true
});

**Comment by 2betop** [comment]
目测你用的是比较老的 node_modules

**Comment by trainGitHub** [comment]
感谢回复，用的是 1.1.7，这版本可以吗，2.x版本稳定了吗

**Comment by 2betop** [comment]
差不多了，目前没有发现什么新 bug

**Comment by trainGitHub** [comment]
嗯 ，我试试新的，感谢

**Comment by trainGitHub** [comment]
看了一下默认装的就是1.1.7版本，哪能下到2.x版本的？

**Comment by trainGitHub** [comment]
这个错误信息太少了，不知道具体在哪出的问题也不懂怎么调试。

**Comment by 2betop** [comment]
nam install -g fis3-hook-node_modules@2.x

**Comment by andycall** [comment]
这个问题是因为你的package.json里面根本就没有devDependencies.

**Comment by trainGitHub** [comment]
是有的，useDev true和false我都试过，我复制了一份，用2.x搞定了，多谢
