### ISSUE TITLE
组件包含的样式会自动载入吗

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis3-hook-node_modules#23]
我现在需要载入一个模块[swiper](https://github.com/nolimits4web/Swiper),可是其package.json中style对应的样式并没有同时载入进来，是需要哪里再显示声明下吗

```
npm install swiper --save
```

```
var Swiper = require('swiper');
```

**Comment by ascoders** [comment]
css再import一下

**Comment by fancyboynet** [comment]
import('swiper')?

**Comment by 2betop** [comment]
```
import 'swiper/dist/css/swiper.css'
```

**Comment by fancyboynet** [comment]
import的方式没试成功，require的方式可行

```
/**
 * @require swiper/dist/css/swiper.css
 */
```

顺便问下，是否考虑这种情形自动引入样式呢，感觉package.json里已经声明了，还需要再显示声明么

**Comment by 2betop** [comment]
import 的方式，需要加个插件就行了 https://github.com/fex-team/fis3-preprocessor-js-require-css

现在还不能识别 package.json 里面的 style 字段，只认 main 字段。
