### ISSUE TITLE
对amd支持不好

### ISSUE THREAD

**Issue by ccqgithub** [fex-team/fis3-hook-node_modules#28]
webuploader没有提供commonjs版本，为使用webuploader，用这个插件配合‘fis3-hook-amd’ + requireJS，会出现如下错误：

Uncaught Error: Module name "node_modules/react/react" has not been loaded yet for context: _. Use require([])

最后改webuploader源码，用commonjs模式才解决~

**Comment by 2betop** [comment]
可以给目标文件配置 `umd2commonjs`: true.

fis3-hook-commonjs 会针对命中的文件做 amd => commonjs 转换。

**Comment by 2betop** [comment]
https://github.com/fex-team/fis3-hook-commonjs#fis3-hook-commonjs
