### ISSUE TITLE
当 es6 文件，设置 isMod 时，编译失败

### ISSUE THREAD

**Issue by ystarlongzi** [fex-team/fis3-hook-node_modules#29]
`fis-conf.js` 配置文件精简后如下：

```
fis.match('*.js', {
    isMod: true
});
fis.match('*.es6', {
    isMod: true,
    rExt: '.js'
});
// 使用 node_modules 加载模块
//fis.hook('commonjs');
//fis.unhook('components');
fis.hook('node_modules');
```

如题，当设置 `fis.hook('node_modules')` 并且 `.es6` 文件配置 `isMod:true` 时，编译提示 `content.replace is not a function`，如果把 `fis.hook('node_modules')` 注释掉，编译就会成功。

另外，使用 [fis3-hook-npm](https://github.com/qqiangwu/fis3-hook-npm) 插件时，无上述问题，编译成功。

还有，想请教下，fis 下插件怎么调试啊？比如刚才提到的报错信息是 `content.replace is not a function`，大致推断出应该是这里的[第33行代码](https://github.com/fex-team/fis3-hook-node_modules/blob/master/lib%2Fbrowserify.js#L33)，但是不知道 content 的具体内容是什么，或者怎么调试设置断点

**Comment by ystarlongzi** [comment]
fis 版本是 v3.3.29

**Comment by 2betop** [comment]
我怀疑是 es6 文件后缀没有被识别为 text , 参考这个里面 #project.fileType.text 配置 http://fis.baidu.com/fis3/docs/api/config-props.html

**Comment by ystarlongzi** [comment]
@2betop 
谢谢，按照你的方案，已经解决了。
