### ISSUE TITLE
不支持私有仓库cnpm?

### ISSUE THREAD

**Issue by chuangker** [fex-team/fis3-hook-node_modules#3]
由于私有仓库package.json -> name字段要加前缀
例: @pq/math

发现在入口文件引入 var math = require('@pq/math'); 能正常编译
但是没有产出到目录

请问是我哪写错了？还是不支持这种模块

**Comment by 2betop** [comment]
不支持，还没考虑过私有仓库这种情况

**Comment by chuangker** [comment]
公司有很多内部模块 那有什么办法解决吗

**Comment by andycall** [comment]
考虑支持一下

**Comment by chuangker** [comment]
好的 谢谢

**Comment by renxia** [comment]
支持node模块好处是极多的，赞

另外index.js末尾的
  fis.on('proccess:start', onPreprocess);
应当为  
 fis.on('process:start', onPreprocess);

**Comment by chuangker** [comment]
好像现在还是不支持私有仓库的安装啊

我尝试在onFileLookUp方法里 将变量 m  的正则做了适当修改 好像可以支持私有仓库了

```
// 加了@
var m = /^([@0-9a-zA-Z\.\-_]+)(?:\/(.+))?$/.exec(rest); 
```

请问这样做可以么

**Comment by 2betop** [comment]
已经支持，请使用 `fis3-hook-node_modules@2.2.1`

**Comment by chuangker** [comment]
好的谢谢 我试试
