### ISSUE TITLE
不支持angular2的带@字符模块@angular的直接同名引入

### ISSUE THREAD

**Issue by luozt** [fex-team/fis3-hook-node_modules#32]
经过实践发现，对于普通的npm模块如jQuery, bootstrap，可以直接同名引入，`require("jquery")`，但在开发angular2时，是安装带@开头的npm模块，就不支持直接同名引入了，如`require("@angular/core")`会报错。本人做了个示例，可看下：[public-static](https://github.com/luozt/public-static)。求解决~

**Comment by 2betop** [comment]
嗯，目前确实不支持 `@` 打头的 包，感谢提供示例，下午看看。

**Comment by lococo--0** [comment]
mark

**Comment by lococo--0** [comment]
@2betop 这个有下文么？最近想把ng2迁到rc，但是这个问题一直卡在这里

**Comment by 2betop** [comment]
fis3-hook-node_modules@2.2.0 开始支持。

**Comment by lococo--0** [comment]
好爱你！！！！！

**Comment by lococo--0** [comment]
@2betop 不会报错了·· 但是好像@angular被ignore掉了, 在发布目录里找不到@angular的发布文件

**Comment by lococo--0** [comment]
忽略我 ·· 好像刚刚是因为缓存
