### ISSUE TITLE
使用fis3-hook-node_modules，import进来的css，怎么设置打包到一个文件中？

### ISSUE THREAD

**Issue by EagleChinaWu** [fex-team/fis3-hook-node_modules#33]
使用fis3-hook-node_modules，结合fis3-preprocessor-js-require-css，import进来的css，怎么设置打包到一个css文件中？

**Comment by 2betop** [comment]
建议先去看看 fis3 的文档，关于文件合并。

http://fis.baidu.com/fis3/docs/lv1.html#%E7%AE%80%E5%8D%95%E5%90%88%E5%B9%B6

**Comment by EagleChinaWu** [comment]
.match('::package', {
    packager: fis.plugin('deps-pack', {
      'static/js/node_modules.js': [
        'modules/index.jsx:deps',
        '!/modules/**'
      ],
      'static/js/public.js':[
        'modules/index.jsx',
        'modules/index.jsx:deps'
      ]
    })
  })

原来和fis3-packager-deps-pack冲突了，去掉这个就好用了。

**Comment by 2betop** [comment]
fis3-packager-deps-pack 也支持 css 打包，配置规则是一样的。
