### ISSUE TITLE
‘process/browser’ not install

### ISSUE THREAD

**Issue by lococo--0** [fex-team/fis3-hook-node_modules#35]
在引入 [reflect-metadata](https://github.com/rbuckton/ReflectDecorators/blob/master/Reflect.js) 的时候，当我设置`isMod: true`总会提示我一个 process/browser 找不到的warning

``` bash
  [WARNI] Can't resolve `process/browser` in file [/node_modules/reflect-metadata/Reflect.js], did you miss `npm install process`?
```

但是我去查这个文件里面只有一个`require('crypto')`
当我把isMod设为false的时候，就没有这个warning了

**Comment by 2betop** [comment]
因为 zone.js 里面有 global 的用法，而 浏览器中并不能运行。所以，自动会在代码顶部加上

`var global = require('process/browser');`

So, 你就执行下 `npm install process` 然后就OK了。

**Comment by lococo--0** [comment]
太棒！好喜欢秒回的issue！
