### ISSUE TITLE
使用系统的node_modules

### ISSUE THREAD

**Issue by feix760** [fex-team/fis3-hook-node_modules#36]
现在只能使用工作目录下的node_modules

我们能够用它改造一下： https://www.npmjs.com/package/require-relative  使用系统的node_modules
可行的话代码也会简化很多。

**Comment by 2betop** [comment]
只能引用工作目录下的文件，包括 node_modules

**Comment by feix760** [comment]
![3048ab7c-e52b-4be3-b70a-6d71cd4518b3](https://cloud.githubusercontent.com/assets/5415656/15668538/615efa74-274e-11e6-94d4-0e85965be9a0.png)
是因为文件不在工作目录下么？我想动态创建系统node_modules里的文件至工作目录下

**Comment by ascoders** [comment]
这个组件是用来打包『业务代码』，把它装在工作目录外项目根本无法维护。

**Comment by feix760** [comment]
@ascoders 
package.json不是还在工作目录么，node_modules只需要维护package.json版本吧，难道直接去改node_modules下的文件？
这样会有一些问题：
1、可以使用fis.project.setProjectRoot('src') 改变ProjectRoot，之后业务node_modules必须放在src/node_modules下，而fis插件需要放在fis.conf同级的node_modules下，这样需要维护两个node_modules
2、src/node_modules可能需要提交到svn/git创库

**Comment by ascoders** [comment]
1.为什么把业务放在src/node_modules下
2.svn 设置 propset， git 添加 .gitignore
