### ISSUE TITLE
不加载peerDependencies

### ISSUE THREAD

**Issue by Yumozhi** [fex-team/fis3-hook-node_modules#4]
fis3-parser-vue依赖中的
vueify-insert-css是vueify-sync的peerDependencies
没有处理peerDependencies导致release时出错

有什么解决的办法么，也加上个选项？

**Comment by andycall** [comment]
peerDependencies 是要你自己手动装的。。 

NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead.

**Comment by Yumozhi** [comment]
这个我在问之前看过了，npm1/2特定条件下会安装，3不会
如果直接依赖我肯定就直接手动装了
问题是依赖的包中有peerDependencies
npm下载了，但是插件不加载
这种情况手动安装会冗余而且总感觉很麻烦..

**Comment by ascoders** [comment]
peerDependencies的意义就是这个模块已经预先装在dependencies里，所以如果没有，就不符合这个包的运行环境。
类似的关系有例如react-dom->peer->react。
所以请手动装不要嫌麻烦。
