### ISSUE TITLE
Cannot find module `node_modules/react-redux/node_modules/lodash/isPlainObject`

### ISSUE THREAD

**Issue by jasonliao** [fex-team/fis3-hook-node_modules#42]
使用 redux 和 react-redux 开发的时候，编译之后报 Cannot find module ’node_modules/react-redux/node_modules/lodash/isPlainObject‘

看了一下 release 之后的目录，`node_modules` 里的 `redux` 里的 `node_module` 有 `lodash` 文件夹，去到 `aio.js` 也看到相关的模块定义代码

``` javascript
define('node_modules/redux/node_modules/lodash/isPlainObject', function () { ... })
```

但是 `react-redux` 里却没有 `lodash` 文件夹，`aio.js` 也没有相关的 `define`

然后怀疑是资源防止重复加载了，但 `mergeLevel` 0 1 都试过了

下面提供一下信息：

``` javascript
// fis-conf.js - key part
fis
  .match('/{node_modules, src}/**.js', {
    isMod: true
  })
  .match('/src/**.js', {
    parser: fis.plugin('babel-5.x', {
      optional: ["es7.decorators", "es7.classProperties"],
      stage: 0
    }),
    rExt: '.js',
    preprocessor: fis.plugin('js-require-css')
  })
  .match('*.scss', {
    parser: fis.plugin('node-sass'),
    rExt: '.css'
  })
  .unhook('components')
  .hook('node_modules', {
    shimBuffer: false,
    mergeLevel: 0
  })
  .hook('commonjs', {
    extList: ['.js']
  })
  .match('::package', {
    postpackager: fis.plugin('loader', {
      allInOne: {
        js: function(file) {
          return '/build/aio.js'
        }
      }
    })
  })
```

redux/lodash -v 4.2.1
react-redux/lodash -v 4.2.0

**Comment by jasonliao** [comment]
其实设置 `mergeLevel` 为 1 或者２都出现构建不成功的问题，release --verbose 发现都卡在了

`pipe [preprocessor.js-require-css] start`  这里 :(  

而且 ubuntu 上 <kbd>Ctrl</kbd> <kbd>c</kbd> 貌似不起作用？

**Comment by 2betop** [comment]
node_modules 可能是 link 的方式安装的，试试不要用 link 的方式。

**Comment by jasonliao** [comment]
@2betop 嗯嗯，用 `npm install` 的确可以了，之前是用 `cnpm` 的，顺便问一下，`cnpm` 有选项是采用 link 还是 非link 的形式吗？
