### ISSUE TITLE
Cannot find module `process/browser`这个怎么解决

### ISSUE THREAD

**Issue by ygtzz** [fex-team/fis3-hook-node_modules#45]
rt

**Comment by 2betop** [comment]
npm install process 然后重新 release

**Comment by ygtzz** [comment]
提重了，谢谢

**Comment by billwing** [comment]
@2betop 貌似`npm install process`之后重新release也不行，发现可能因为源文件没有`require(‘process/browser’)`，然后fis3没识别到就没复制到`output/node_modules`里面？
