### ISSUE TITLE
使用这个插件后，只能用node安装的模块？

### ISSUE THREAD

**Issue by codering** [fex-team/fis3-hook-node_modules#6]
这样的，我重写定义模块ID,  `/module/widget/xxx/xxx.js`  --> `widget/xxx`

``` js
fis.match(/^\/module\/(.*\/([^\/]+))\/\2\.js$/, {
    id: "$1"
});
```

然后require("widget/xxx") ,  release 时找不到。[ERROR] Cannot find module 'widget/xxx' from .....

**Comment by 2betop** [comment]
如果想要短路径引用，请设置 paths 或者 packages 之类的, 不要修改 fis 的资源 id。如：

```
fis.hook('commonjs', {
  paths: {
    widget: './module/'
  }
})
```

**Comment by 2betop** [comment]
不过这个报错，确实需要这个插件里面处理下。应该是 warning
