### ISSUE TITLE
demo 跑不起来

### ISSUE THREAD

**Issue by Coffcer** [fex-team/fis3-hook-node_modules#9]
![image](https://cloud.githubusercontent.com/assets/12846955/13699191/d0954e00-e7b3-11e5-8ad9-fc1f1985011c.png)

node的版本是v4.2.4
fis3的版本是v3.3.15

**Comment by andycall** [comment]
你确定你是在demo目录下运行`fis3 release -cd ./output` ?

**Comment by Coffcer** [comment]
Sorry, 是我自己的问题
